### ISSUE TITLE
Can't add 'Host' or 'Content-Length' to Order Map via setting them to nil

### ISSUE THREAD

**Issue by shrimpwtf** [gospider007/requests#11]
Hey!
OrderMap's need a new technique to add keys into them without setting a value for dynamically computed headers, I was spending ages last night diagnosing an issue which ended up being setting Content-Length to nil to try and add just the key into the map, however doesn't seem possible. Please modify OrderMap's to be able to just add a key into the internal order slice. Thankyou :)

**Comment by gospider007** [comment]
https://github.com/gospider007/requests/blame/master/test/fingerprint/ja4_test.go#L53
