### ISSUE TITLE
link: github.com/gospider007/requests: invalid reference to net/http.readCookies

### ISSUE THREAD

**Issue by isheperserga** [gospider007/requests#13]
This issue started happening all of a sudden, no clue why honestly.

```go
package main

import (
	"context"
	"github.com/gospider007/requests"
)

func main() {
	requests.NewClient(context.TODO())
}
```

This is the full code, on go run, it errors out:

link: github.com/gospider007/requests: invalid reference to net/http.readCookies

Extremely weird :/

I'm on Go 1.22.6

**Comment by gospider007** [comment]
go 1.23.0 导致的问题，最新版已修复
