### ISSUE TITLE
Ja3 spec random

### ISSUE THREAD

**Issue by drRobertDev** [gospider007/requests#19]
Cause missing last version Edge/Chrome template i using ja3 with ja3.CreateSpecWithStr(...)

as you know Extensions part of ja3 is random on last real edge/chrome browser, is possible do something like it, cause cretespeckwithstr is always same.

From last Edge browser, session 1 and 2 :

772,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,  23-5-13-18-10-43-27-17513-16-51-65281-11-35-65037-45-0,   25497-29-23-24,0

772,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53, 35-11-23-27-10-16-65037-51-17513-18-65281-43-5-0-45-13    ,25497-29-23-24,0

thanks

**Comment by gospider007** [comment]
ja3.CreateSpecWithStr 你传的值是相同的，生成的指纹肯定是相同的呀，你随机下你的指纹不就好了吗
