### ISSUE TITLE
No option to set no "Referer" Header

### ISSUE THREAD

**Issue by fr-edy** [gospider007/requests#24]
Hey,

I don't see any reason why the client should set a mandatory "Referer"-Header if there is not "Referer" header passed in the request. 

Example:

If you would imitate an initial request to a website it does not make sense that the request would already have the "Referer" header which is the wanted url as it has never been on the page. Further more when interacting with APIs it is very uncommon to pass a "Referer" header.

Thank you for your library and hopefully you can make an option for that.

**Comment by gospider007** [comment]
已经修复了，最新版本不强制设置Referer

**Comment by fr-edy** [comment]
Thank you very much.
