### ISSUE TITLE
The headers in a request automatically get converted to uppercase.

### ISSUE THREAD

**Issue by 0xfocu5** [gospider007/requests#27]
[parseHeaders](https://github.com/gospider007/requests/blob/master/body.go)
The `header.Add` function will internally call `textproto.CanonicalMIMEHeaderKey` to standardize the header names, which results in capitalizing the first letter of each word and making all other letters lowercase. However, some servers can only recognize headers written entirely in lowercase. Here's some test code that demonstrates this behavior:

```
header := http.Header{}
header.Add("content-type", "application/json")
fmt.Println(header) 
fmt.Println(textproto.CanonicalMIMEHeaderKey("content-type"))  // print: Content-Type 
fmt.Println(textproto.CanonicalMIMEHeaderKey("x-auth"))        // print: X-Auth 
fmt.Println(textproto.CanonicalMIMEHeaderKey("accept-encoding")) // print: Accept-Encoding
```

**Comment by gospider007** [comment]
https://github.com/gospider007/requests/blob/master/test/fingerprint/ja4_test.go

**Comment by 0xfocu5** [comment]
> https://github.com/gospider007/requests/blob/master/test/fingerprint/ja4_test.go

I got it. thanks a lot
