### ISSUE TITLE
why response cookie don't work in next request ?

### ISSUE THREAD

**Issue by opvexe** [gospider007/requests#3]
<img width="670" alt="image" src="https://github.com/gospider007/requests/assets/26895243/056c0d6d-c6e7-4e62-a9f3-22db69504707">
<img width="262" alt="image" src="https://github.com/gospider007/requests/assets/26895243/c834806e-dced-431a-a1ff-1860d7c817dc">

上一个请求返回的reposonse cookie 为什么在下一个请求的时候，没有？为什么

**Comment by gospider007** [comment]
Do you have a reproducible demo?

**Comment by gospider007** [comment]
经过测试没有复现这个bug

**Comment by opvexe** [comment]
> 经过测试没有复现这个bug

我第一次请求返回的cookie 为什么在第二次请求的时候，我看请求里没有cookie ? 为什么？

<img width="615" alt="image" src="https://github.com/gospider007/requests/assets/26895243/8ee427fb-a00c-4e47-b1f7-a29e7ce175e4">

<img width="571" alt="image" src="https://github.com/gospider007/requests/assets/26895243/4d298ec0-ac1a-48c1-88a5-9b2a460f60e9">

我这样写有问题吗？

<img width="1001" alt="image" src="https://github.com/gospider007/requests/assets/26895243/3af8e59a-c519-48e4-99ed-a11f652073d9">

一直是空的，上一次请求返回在response的cookie 并没有在下一次自动带上

**Comment by opvexe** [comment]
我知道了 
<img width="635" alt="image" src="https://github.com/gospider007/requests/assets/26895243/23fe1fc9-a0b2-4bd3-9fe3-e1ae4d90bdee">
